[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#4c1d95"
secondaryBackgroundColor = "#8b5cf6"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
